https://techcommunity.microsoft.com/blog/azuretoolsblog/announcing-public-preview-of-terraform-export-from-the-azure-portal/4409889


LifeDojo / New York / Sr Software Engineer / June 2017 –  Dec 2017
Environment: JavaScript, React.js, Redux, Material-UI, CSS, HTML, GIT, Webpack.
	•	Implemented the Coach-Coachee communication modules.
	•	Used Twilio cloud api to develop the chat widgets. 
	•	Implemented middleware module for token management.
	•	Integrated the legacy Coach admin module into the new app.
	•	Refactored the user accounts pages which used the Backbone library.
	•	Interacted with stakeholders to get the requirements and built the new responsive version of the app.
	•	Coordinated with offshore team to get the UI assets implemented.

Macmillan Learning / New York / Sr Software Consultant / April 2014 –  March 2017
Environment: JavaScript, React.js, JQuery, CSS, HTML, GIT, Gulp, Jasmine, Karma.
	•	Designed and developed generic and accessibility compliant widgets for the Next-Gen application. 
	•	Implemented the Table-Of-Content widget used in the content home page, which is built dynamically after parsing the JSON data returned from a service API.
	•	Designed and developed a generic data store REST API using Mongodb and Node.js
	•	Implemented the SCORM standard based Assessment UI module for Macmillan's flag ship LMS product which consisted of Quiz settings & assignment module, Questions creation/editing module.
	•	Interfaced with the backend API to store and retrieve data, which is derived from Agilix a third party vendor.
	•	Successfully converted all ASP.NET Razor templates to single page app using React.js
	•	Analysis of critical production issues using tools like New-Reliq, Splunk, Chrome Dev tools, Fiddler and internal test & debugging tools.

Echo  / New York / Solutions Engineer / May 2013 –  April 2014
Environment: JavaScript, JQuery, CSS, HTML, GIT.
	•	Worked with cross-functional teams to guide the development and presentation of social solutions that drive client business.
	•	Assisted CNN to build a proprietary login system for Echo’s apps using BackPlane protocol.
	•	Built web pages using core Echo api with RealTime stream of user’s Social Media posts for clients like WWE, DirectTV, Rockettes, iVillage etc.

Audible Inc. / New York / Sr Software Consultant / Jul 2011 –  Feb 2013 
Environment: JavaScript, JQuery, Java, JSTL, Selenium, Spring, Hibernate, TestNG.
	•	Ported the Audible German site from the old Broad-vision based e-commerce portal to Amazon’s e-commerce web portal on Santana platform.
	•	Created various reusable pagelets used in the Audible German site. 
	•	Developed test cases using Selenium and TestNG for build verification step of the continuous build process. 


Time Inc. / New York / Sr Software Consultant / Mar 2011 – Jul 2011 
Environment : Java, JavaScript, Spring, Hibernate, Oracle, Maven
	•	Designed and developed the subscriptions module using  Java and Spring framework.

Conde Nast Digital. / New York  / Sr Software Consultant / Jan 2010 – Feb 2011
Environment: JavaScript , JSP, XML, XSL, XSD, CSS, Java, Spring, Hibernate, Groovy, Oracle
	•	Involved in design and development of the presentation layer for Conde-Nast magazines.
	•	Leveraged Spring MVC/DI/AOP and Spring DAO in various application modules.

Common Need, Inc. / New York / Sr Software Consultant / June 2009 – Jan 2010
Environment: Groovy & Grails, JavaScript, GWT, CSS, JQuery, My SQL
	•	Built UI modules for the social network based educational product.    
	•	Automated functional testing using selenium plug-in.

Blank Slate Factory, Inc. / New York / Sr Software Consultant  / June 2008 – May 2009
Environment: Java, Spring, Hibernate, Acegi  (Spring) Security,  SVN, My SQL, JavaScript , JSP, XML 
	•	Developed enterprise-grade web application from the ground up using leading open source technologies in a highly agile environment. 
	•	Responsible for all the core algorithms for schema independence, data type mapping, data transformation which are the main pillars of the product using Java, Hibernate and Spring. 

Hillcrest Labs / Maryland / Software Consultant through MindTree / Nov 2006 - Dec 2007
Environment: Java, J2ME, J2EE, JMS, Linux, Oracle 9i, JBoss, XML, JavaScript, Test Director.
	•	Involved in analysis of business requirements and convey the design to the offshore team. 
	•	Developed UI modules for the digital home navigation system. 

MindTree Consulting / Bangalore / Sr Software Engineer / Feb 2004  - Oct 2006
Clients: Cisco, Texas Instruments	
Environment: Java, J2EE, EJB, JDBC, Servlets, JSP, JSTL, Struts, Perl, JavaScript, XML, JMS, J2ME, Oracle 8i, Web Services (SOAP and WSDL)
	•	Worked on Network Management System projects using Java technologies.   



------------
https://clemenssiebler.com/posts/sharing-azure-openai-provisioned-throughput-ptu-multiple-use-cases-api-management/
https://learn.microsoft.com/en-us/rest/api/support/quota-payload
https://learn.microsoft.com/en-us/azure/ai-services/openai/how-to/quota?tabs=rest#automate-deployment
!!!
https://github.com/Azure/aoai-apim
https://github.com/microsoft/AzureOpenAI-with-APIM/blob/main/example_code/example.py
https://github.com/Azure/azure-rest-api-specs/blob/main/specification/cognitiveservices/data-plane/AzureOpenAI/inference/stable/2024-10-21/inference.json
https://github.com/microsoft/AzureOpenAI-with-APIM#tying-it-all-together
https://techcommunity.microsoft.com/blog/appsonazureblog/calculating-chargebacks-for-business-unitsprojects-utilizing-a-shared-azure-open/3909202
------------

Open img - https://medium.com/@loganoop/deploy-azure-ai-services-on-docker-container-534ca5422de5

Az cantiner  https://learn.microsoft.com/en-us/azure/ai-services/cognitive-services-container-support

https://medium.com/@its.me.siddh/dockerize-your-gpt-3-a-guide-to-running-chatgpt-locally-on-your-machine-d5f42d14beb7

-deploy mdl 2 eks https://docs.datarobot.com/en/docs/integrations/aws/deploy-dr-models-on-aws.html

Arm - https://stackoverflow.com/questions/52544314/use-azure-arm-template-to-create-an-aks-cluster-and-deploy-my-kubernetes-applica


https://oxyprogrammer.com/understanding-cqrs-and-event-sourcing-a-path-to-more-robust-distributed-systems


import json

def filter_names_by_prefix(filename, prefix="ap"):
  """
  Parses a JSON file and returns a list of records where the "name" field starts with the given prefix.

  Args:
      filename (str): Path to the JSON file.
      prefix (str, optional): The prefix to filter names by. Defaults to "ap".

  Returns:
      list: A list of dictionaries containing the filtered records.
  """

  with open(filename, 'r') as f:
    data = json.load(f)

  filtered_records = [record for record in data if record["name"].startswith(prefix)]
  return filtered_records

if __name__ == "__main__":
  filename = "your_json_file.json"  # Replace with your actual filename
  filtered_data = filter_names_by_prefix(filename)
  print("Records with names starting with 'ap':")
  print(filtered_data)


https://techcommunity.microsoft.com/t5/ai-azure-ai-services-blog/azure-openai-service-announces-assistants-api-new-models-for/ba-p/4049940


    Insights Application Insight identifies exceptions thorough all of the components of your applications. Insights are available for Container, VM, Network, Storage and Additional Solutions.
https://techcommunity.microsoft.com/t5/ai-azure-ai-services-blog/azure-openai-service-announces-assistants-api-new-models-for/ba-p/4049940


https://cloud.google.com/blog/topics/cost-management/principles-of-cloud-cost-optimization


https://github.com/Azure-Samples/openai-python-enterprise-logging

https://learn.microsoft.com/en-us/azure/cognitive-services/openai/overview

https://learn.microsoft.com/en-us/azure/cognitive-services/openai/how-to/monitoring

https://learn.microsoft.com/en-us/azure/azure-monitor/logs/data-platform-logs

https://journeyofthegeek.com/tag/azure-openai-service/

https://journeyofthegeek.com/2023/04/13/logging-in-azure-openai-service/

https://learn.microsoft.com/en-us/azure/azure-monitor/app/live-stream?tabs=dotnet6

https://learn.microsoft.com/en-us/azure/azure-monitor/app/app-insights-overview?tabs=net

-----

azure api developer portal publish blocked by subnet

https://srigunnala.com/apim-internalmode/

https://social.msdn.microsoft.com/Forums/en-US/a9e533b6-dec5-418d-bc5a-2dc58fc51a78/api-management-internal-vnet-developer-portal-not-available?forum=azureapimgmt

https://learn.microsoft.com/en-us/azure/api-management/api-management-howto-integrate-internal-vnet-appgateway

https://learn.microsoft.com/en-us/azure/api-management/api-management-using-with-internal-vnet?tabs=stv2



----

https://learn.microsoft.com/en-us/azure/developer/terraform/deploy-application-gateway-v2

https://www.jeanpaulsmit.com/2020/03/terraform-deploy-apim/
https://rakesh-suryawanshi.medium.com/deploying-api-management-with-terraform-5a755f7434df
https://github.com/claranet/terraform-azurerm-api-management

https://docs.microsoft.com/en-us/azure/devops/organizations/settings/naming-restrictions?view=azure-devops

https://www.clouddirect.net/knowledge-base/KB0011467/azure-file-naming-and-referencing-restrictions

https://docs.microsoft.com/en-us/rest/api/storageservices/naming-and-referencing-shares--directories--files--and-metadata

https://www.drware.com/azure-policy-whats-the-length-of-policy-assignments-name/
https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/resource-name-rules#microsoftauthorization

https://docs.microsoft.com/en-us/azure/governance/policy/concepts/definition-structure
https://docs.microsoft.com/en-us/azure/governance/policy/concepts/policy-as-code
https://docs.microsoft.com/en-us/azure/governance/policy/overview

Directory: Title case
File name: <dir>_<description>_<conditionals(optional)>




Azure resource names can't be renamed hence name it correctly when creating.
Able to search and browse for azure resources. 
Descriptive enough to know what the resource is in the context of the infrastructure.
Indicates the role and ownership of a resource.
Promote consistency within an infrastructure.
Allows to sort and filter resources quickly.

<deptment>-<env>-<service short name>-rg , upto 90 chars
https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/resource-name-rules

