= To Create a Server (EU Control Plane)

[NOTE]
From the EU control plane, you can only create servers using Mule Runtime Agent version 1.9.2 and later. Ensure that you have installed this version in your Mule runtime environment.

To manage a remote server from the EU control plane you must run the `amc_setup` script to create a server by configuring the Runtime Manager Agent to communicate with Runtime Manager. 

The procedures for creating a server are similar to those for creating a server in the US control plane. The difference is that you must use the `--region eu1` option when running `amc_setup` as shown in the following example:

----
./amc_setup --region eu1 -H 1234321xyzabc----16 your-eu-server-name
----

This flag ensures that the server connects to Runtime Manager in the EU control plane. When you click Add Server in the  Runtime Manager > Servers tab, Runtime Manager in the EU control plane automatically inserts this flag in the generated script.

== See Also

* link:/runtime-manager/servers-create[To Create a Server in Runtime Manager (Hybrid)]
* link:/eu-control-plane/platform-access-eu[To Access the EU Control Plane]

https://sgryt.com/posts/ocp-in-lambda/

https://sgryt.com/posts/srp-in-lambda/

https://sgryt.com/posts/monolithic-to-microservices-with-lambda/

https://collin-smith.medium.com/improving-performance-of-aws-serverless-applications-with-cqrs-92a8a2a4b60e

https://www.linkedin.com/pulse/top-microservices-patterns-explained-using-aws-swapnil-gholap/

https://blowstack.com/cheat-sheets/aws-microservices-cheat-sheet-key-patterns-services-and-concepts.pdf

https://docs.aws.amazon.com/prescriptive-guidance/latest/patterns/simplify-amazon-eks-multi-tenant-application-deployment-by-using-flux.html

https://github.com/miyagis-forests/farmacy-food-kata/blob/main/architecture/aws-deployment-view.md

https://oxyprogrammer.com/understanding-cqrs-and-event-sourcing-a-path-to-more-robust-distributed-systems

https://sgryt.com/posts/serverless-transition-exploration-with-aws/
